//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reductech.EDR.Core.Internal.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages_EN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages_EN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Reductech.EDR.Core.Internal.Errors.ErrorMessages-EN", typeof(ErrorMessages_EN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assertion Failed &apos;{0}&apos;.
        /// </summary>
        internal static string AssertionFailed {
            get {
                return ResourceManager.GetString("AssertionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert a nested entity to {0}..
        /// </summary>
        internal static string CannotConvertNestedEntity {
            get {
                return ResourceManager.GetString("CannotConvertNestedEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert nested list to {0}..
        /// </summary>
        internal static string CannotConvertNestedList {
            get {
                return ResourceManager.GetString("CannotConvertNestedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create an instance of {0}&lt;{1}&gt;.
        /// </summary>
        internal static string CannotCreateGeneric {
            get {
                return ResourceManager.GetString("CannotCreateGeneric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} cannot create a scoped context.
        /// </summary>
        internal static string CannotCreateScopedContext {
            get {
                return ResourceManager.GetString("CannotCreateScopedContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not infer type.
        /// </summary>
        internal static string CannotInferType {
            get {
                return ResourceManager.GetString("CannotInferType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters {0} and {1} are in conflict..
        /// </summary>
        internal static string ConflictingParameters {
            get {
                return ResourceManager.GetString("ConflictingParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not convert entity value to {0}..
        /// </summary>
        internal static string CouldNotConvertEntityValue {
            get {
                return ResourceManager.GetString("CouldNotConvertEntityValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not parse &apos;{0}&apos; as {1}.
        /// </summary>
        internal static string CouldNotParse {
            get {
                return ResourceManager.GetString("CouldNotParse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve variable &apos;{0}&apos;.
        /// </summary>
        internal static string CouldNotResolveVariable {
            get {
                return ResourceManager.GetString("CouldNotResolveVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Reading CSV.
        /// </summary>
        internal static string CSVError {
            get {
                return ResourceManager.GetString("CSVError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory does not exist or could not be found: &apos;{0}&apos;.
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to Divide by Zero..
        /// </summary>
        internal static string DivideByZero {
            get {
                return ResourceManager.GetString("DivideByZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Parameter: {0}..
        /// </summary>
        internal static string DuplicateParameter {
            get {
                return ResourceManager.GetString("DuplicateParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCL is empty..
        /// </summary>
        internal static string EmptySequence {
            get {
                return ResourceManager.GetString("EmptySequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Process Failed: &apos;{0}&apos;.
        /// </summary>
        internal static string ExternalProcessError {
            get {
                return ResourceManager.GetString("ExternalProcessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External process {0} did not return an output of the expected form.
        /// </summary>
        internal static string ExternalProcessMissingOutput {
            get {
                return ResourceManager.GetString("ExternalProcessMissingOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find process &apos;{0}&apos;.
        /// </summary>
        internal static string ExternalProcessNotFound {
            get {
                return ResourceManager.GetString("ExternalProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index was outside the bounds of the array..
        /// </summary>
        internal static string IndexOutOfBounds {
            get {
                return ResourceManager.GetString("IndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; cannot take the value &apos;{1}&apos;.
        /// </summary>
        internal static string InvalidCast {
            get {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get context &apos;{0}&apos;.
        /// </summary>
        internal static string MissingContext {
            get {
                return ResourceManager.GetString("MissingContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was missing or empty..
        /// </summary>
        internal static string MissingParameter {
            get {
                return ResourceManager.GetString("MissingParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get settings: {0}.
        /// </summary>
        internal static string MissingStepSettings {
            get {
                return ResourceManager.GetString("MissingStepSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get settings value: {0}.{1}.
        /// </summary>
        internal static string MissingStepSettingsValue {
            get {
                return ResourceManager.GetString("MissingStepSettingsValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; does not exist..
        /// </summary>
        internal static string MissingVariable {
            get {
                return ResourceManager.GetString("MissingVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement &apos;{0}&apos; not met..
        /// </summary>
        internal static string RequirementNotMet {
            get {
                return ResourceManager.GetString("RequirementNotMet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Invalid: No Enum name defined.
        /// </summary>
        internal static string SchemaInvalidMissingEnum {
            get {
                return ResourceManager.GetString("SchemaInvalidMissingEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchemaInvalid: No Enum values defined.
        /// </summary>
        internal static string SchemaInvalidNoEnumValues {
            get {
                return ResourceManager.GetString("SchemaInvalidNoEnumValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Violated: Missing Property: &apos;{0}&apos;.
        /// </summary>
        internal static string SchemaViolationMissingProperty {
            get {
                return ResourceManager.GetString("SchemaViolationMissingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Violated: Did not expect a list.
        /// </summary>
        internal static string SchemaViolationUnexpectedList {
            get {
                return ResourceManager.GetString("SchemaViolationUnexpectedList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Violated: Expected not null.
        /// </summary>
        internal static string SchemaViolationUnexpectedNull {
            get {
                return ResourceManager.GetString("SchemaViolationUnexpectedNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Violated: Unexpected Property: &apos;{0}&apos;.
        /// </summary>
        internal static string SchemaViolationUnexpectedProperty {
            get {
                return ResourceManager.GetString("SchemaViolationUnexpectedProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Violated: &apos;{0}&apos; does not match regex &apos;{1}&apos;.
        /// </summary>
        internal static string SchemaViolationUnmatchedRegex {
            get {
                return ResourceManager.GetString("SchemaViolationUnmatchedRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Violated: &apos;{0}&apos; is not a {1}.
        /// </summary>
        internal static string SchemaViolationWrongType {
            get {
                return ResourceManager.GetString("SchemaViolationWrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Syntax Error: {0}.
        /// </summary>
        internal static string SCLSyntaxError {
            get {
                return ResourceManager.GetString("SCLSyntaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} should be a single character, but was &apos;{1}&apos;..
        /// </summary>
        internal static string SingleCharacterExpected {
            get {
                return ResourceManager.GetString("SingleCharacterExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string StepDoesNotExist {
            get {
                return ResourceManager.GetString("StepDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Error Message: &apos;{0}&apos;.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type {0} is not comparable and so cannot be used for sorting..
        /// </summary>
        internal static string TypeNotComparable {
            get {
                return ResourceManager.GetString("TypeNotComparable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enum &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string UnexpectedEnumType {
            get {
                return ResourceManager.GetString("UnexpectedEnumType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected {0}: {1}.
        /// </summary>
        internal static string UnexpectedEnumValue {
            get {
                return ResourceManager.GetString("UnexpectedEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Parameter &apos;{0}&apos; in &apos;{1}&apos;.
        /// </summary>
        internal static string UnexpectedParameter {
            get {
                return ResourceManager.GetString("UnexpectedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An SCL Sequence should have a final return type of Unit. Try wrapping your sequence with &apos;Print&apos;..
        /// </summary>
        internal static string UnitExpected {
            get {
                return ResourceManager.GetString("UnitExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Error: &apos;{0}&apos;.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was a {1}, not a {2}.
        /// </summary>
        internal static string WrongParameterType {
            get {
                return ResourceManager.GetString("WrongParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variable &apos;{0}&apos; does not have type &apos;{1}&apos;..
        /// </summary>
        internal static string WrongVariableType {
            get {
                return ResourceManager.GetString("WrongVariableType", resourceCulture);
            }
        }
    }
}
